### ISSUE TITLE
GroupHeader and HiddenColumns don't work together

### ISSUE THREAD

**Issue by rajendrakesarwani** [oria/gridx#189]
If you have used both "GroupHeader" and "HiddenColumns" in one sample, it does not work together.
Issue 1:- If you hide all the columns one by one and then show any column, you will notice "Header Grouping" has gone.

Issue 2:- If you hide any non grouped header column, you will notice that grouped column became ungrouped.

Note:- I know that both the modules are mentioned incompatible in your compatible matrix.

Thanks & Regards
Rajendra Kumar

**Comment by chenzhh** [comment]
Fixed with commit:
https://github.com/oria/gridx/commit/96631

**Comment by maniprataprana** [comment]
@chenzhh  It's still not working correctly. When a column is hidden, the next available column is taken under the column header. Please check the attached example for code
[Archive.zip](https://github.com/oria/gridx/files/236251/Archive.zip)
